describe('blogs', function () {
  beforeEach(function () {
    cy.request('POST', 'http://localhost:3003/api/testing/reset')
    const user = {
      username: 'testaaja',
      password: 'salainen'
    }

    cy.request('POST', 'http://localhost:3003/api/user', user)
    cy.visit('http://localhost:3000')
  })

  it('logs in', function () {
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
  })

  it('creates a new blog', function () {
    cy.clearLocalStorage()
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="new-blog"]')
      .click()
    cy.get('#title')
      .type('otsikko')
    cy.get('#author')
      .type('kirjailija')
    cy.get('#url')
      .type('uusi')
    cy.get('[data-cy="submit-new-blog"]')
      .click()
  })

  it('shows users page', function () {
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="users"]')
      .click()
    cy.contains('blogs created')
  })

  it('shows blogs page', function () {
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="users"]')
      .click()
    cy.contains('blogs created')
  })

  it('displays new blog in blogs section', function () {
    cy.clearLocalStorage()
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="new-blog"]')
      .click()
    cy.get('#title')
      .type('otsikko')
    cy.get('#author')
      .type('kirjailija')
    cy.get('#url')
      .type('uusi')
    cy.get('[data-cy="submit-new-blog"]')
      .click()
    cy.get('[data-cy="blog-otsikko"]')
      .click()
    cy.contains('Comments')
  })

  it('makes a comment', function () {
    cy.clearLocalStorage()
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="new-blog"]')
      .click()
    cy.get('#title')
      .type('otsikko')
    cy.get('#author')
      .type('kirjailija')
    cy.get('#url')
      .type('uusi')
    cy.get('[data-cy="submit-new-blog"]')
      .click()
    cy.get('[data-cy="blog-otsikko"]')
      .click()
    cy.get('textarea')
      .type('uusi kommentti')
    cy.get('[data-cy="add-comment"]')
      .click()
    cy.contains('Anon')
  })

  it('likes a blog', function () {
    cy.clearLocalStorage()
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="new-blog"]')
      .click()
    cy.get('#title')
      .type('otsikko')
    cy.get('#author')
      .type('kirjailija')
    cy.get('#url')
      .type('uusi')
    cy.get('[data-cy="submit-new-blog"]')
      .click()
    cy.get('[data-cy="blog-otsikko"]')
      .click()
    cy.get('[data-cy="like"]')
      .click()
    cy.contains('1 likes')
  })

  it('removes a blog', function () {
    cy.clearLocalStorage()
    cy.get('#username')
      .type('testaaja')
    cy.get('#password')
      .type('salainen')
    cy.get('button')
      .click()
    cy.get('[data-cy="new-blog"]')
      .click()
    cy.get('#title')
      .type('otsikko')
    cy.get('#author')
      .type('kirjailija')
    cy.get('#url')
      .type('uusi')
    cy.get('[data-cy="submit-new-blog"]')
      .click()
    cy.get('[data-cy="blog-otsikko"]')
      .click()
    cy.get('[data-cy="remove"]')
      .click()
    cy.contains('deleted blog "otsikko"')
  })
})